#username: RathamaMaster
# password: Un13@3H*Th38*&al!

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rathamamaster
  password: Un13@3H*Th38*&al!
  host: localhost

development:
  <<: *default
  database: RathamaDB_Development

test:
  <<: *default
  database: your_test_db_name

production:
  <<: *default
  database: your_production_db_name
  username: your_production_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: your_production_host
