local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

development:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

staging:
  service: Disk
  root: /data # Render's persistent disk mount point for development/staging

production:
  service: Disk
  root: /data # Adjust if production uses a different path or service (e.g., AWS S3)
